service: firstbot

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}  # default to dev if not specified on command-line
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action: secretsmanager:GetSecretValue
      Resource: 
        - arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:botty-api-key-QaEzuG
        - arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:botty-signing-key-bHHrH1

functions:
  hello:
    handler: slackevent.handler
    events:
      - http:
          path: "/events"
          method: post

environment:
  LOGLEVEL: DEBUG

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-domain-manager

custom:
  customDomain:
    domainName: botty.fora9err.com
    stage: dev
    certificateName: '*.fora9err.com'
